version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "pwd123qwe!"
      ACCEPT_EULA: "Y"
    volumes:
      - D:\estudo\db\sqlserver\data:/var/opt/mssql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G